### ISSUE TITLE
investigate assertion in `updateSourceFile`

### ISSUE THREAD

**Issue by ajafff** [fimbullinter/wotan#361]
I noticed this while working on `no-duplicate-spread-property.ts`:

```ts
import { TypedRule, excludeDeclarationFiles, requiresCompilerOption } from '@fimbul/ymir';
import * as ts from 'typescript';
import { isReassignmentTarget, isObjectType, unionTypeParts, isClassLikeDeclaration, getPropertyName } from 'tsutils';
import { lateBoundPropertyNames } from '@fimbul/mimir/src/utils';

interface PropertyInfo {
    known: boolean;
    names: ts.__String[];
    assignedNames: ts.__String[];
}

const emptyPropertyInfo: PropertyInfo = {
    known: false,
    names: [],
    assignedNames: [],
};

@excludeDeclarationFiles
@requiresCompilerOption('strictNullChecks')
export class Rule extends TypedRule {
    public apply() {
        const checkedObjects = new Set<number>();
        for (const node of this.context.getFlatAst()) {
            if (
                node.kind === ts.SyntaxKind.SpreadAssignment &&
                !checkedObjects.has(node.parent!.pos) &&
                !isReassignmentTarget(<ts.ObjectLiteralExpression>node.parent)
            ) {
                checkedObjects.add(node.parent!.pos);
                this.checkObject(<ts.ObjectLiteralExpression>node.parent);
            }
        }
    }

    private checkObject({properties}: ts.ObjectLiteralExpression) {
        const propertiesSeen = new Set<ts.__String>();
        for (let i = properties.length - 1; i >= 0; --i) {
            const property = properties[i];
            const info = this.getPropertyInfo(property);
            if (info.known && info.names.every((name) => propertiesSeen.has(name))) {
                if (property.kind === ts.SyntaxKind.SpreadAssignment) {
                    this.addFailureAtNode(property, 'All properties of this object are overridden later.');
                } else {
                    this.addFailureAtNode(property.name, `Property '${property.name.getText(this.sourceFile)}' is overridden later.`);
                }
            }
            for (const name of info.assignedNames)
                propertiesSeen.add(name);
        }
    }

    private getPropertyInfo(property: ts.ObjectLiteralElementLike): PropertyInfo {
        switch (property.kind) {
            case ts.SyntaxKind.SpreadAssignment:
                return this.getPropertyInfoFromSpread(property.expression);
            case ts.SyntaxKind.ShorthandPropertyAssignment:
                return {
                    known: true,
                    names: [property.name.escapedText],
                    assignedNames: [property.name.escapedText],
                };
            default: {
                const staticName = getPropertyName(property.name);
                if (staticName !== undefined) {
                    const escapedName = ts.escapeLeadingUnderscores(staticName);
                    return {
                        known: true,
                        names: [escapedName],
                        assignedNames: [escapedName],
                    };
                }
                const lateBound = lateBoundPropertyNames((<ts.ComputedPropertyName>property.name).expression, this.checker);
                if (!lateBound.known)
                    return emptyPropertyInfo;
                const names = lateBound.properties.map((p) => p.symbolName);
                return {
                    names,
                    known: true,
                    assignedNames: names.length !== 1 ? [] : names, // if the computed name is a union, it's not sure which will be assigned
                }
            }
        }
    }

    private getPropertyInfoFromSpread(node: ts.Expression): PropertyInfo {
        const type = this.checker.getTypeAtLocation(node)!;
        return unionTypeParts(type).map(getPropertyInfoFromType).reduce(combinePropertyInfo);
    }
}

function getPropertyInfoFromType(type: ts.Type): PropertyInfo {
    if (!isObjectType(type))
        return emptyPropertyInfo;
    const result: PropertyInfo = {
        known: (type.flags & (ts.TypeFlags.Any | ts.TypeFlags.Unknown)) !== 0 ||
            type.getStringIndexType() === undefined && type.getNumberIndexType() === undefined,
        names: [],
        assignedNames: [],
    };
    for (const prop of type.getProperties()) {
        if (isClassMethod(prop))
            continue;
        if ((prop.flags & ts.SymbolFlags.Optional) === 0)
            result.assignedNames.push(prop.escapedName);
        result.names.push(prop.escapedName);
    }
    return result;
}
function isClassMethod(prop: ts.Symbol): boolean | undefined {
    if (prop.flags & ts.SymbolFlags.Method && prop.declarations !== undefined)
        for (const declaration of prop.declarations)
            if (isClassLikeDeclaration(declaration.parent!))
                return true;
    return false;
}

function combinePropertyInfo(a: PropertyInfo, b: PropertyInfo): PropertyInfo {
    return {
        known: a.known && b.known,
        names: [...a.names, ...b.names],
        assignedNames: a.assignedNames.filter((name) => b.assignedNames.includes(name)),
    };
}

```

Running the above code with `wotan -m ./packages/valtyr --fix` fixes the missing semicolon near the end of `getPropertyInfo`. Afterwards `arrow-parens` kicks in and wants to add parens in line 121 (`combinePropertyInfos`, `assignedNames`). Updating a second time fails with:

```
Error: Debug Failure. False expression.
    at adjustIntersectingElement (/Users/klaus/code/wotan/node_modules/typescript/lib/typescript.js:21753:26)
    at visitNode (/Users/klaus/code/wotan/node_modules/typescript/lib/typescript.js:21792:21)
    at visitArray (/Users/klaus/code/wotan/node_modules/typescript/lib/typescript.js:21825:25)
    at visitNodes (/Users/klaus/code/wotan/node_modules/typescript/lib/typescript.js:15236:24)
    at forEachChild (/Users/klaus/code/wotan/node_modules/typescript/lib/typescript.js:15466:24)
    at visitNode (/Users/klaus/code/wotan/node_modules/typescript/lib/typescript.js:21793:21)
    at updateTokenPositionsAndMarkElements (/Users/klaus/code/wotan/node_modules/typescript/lib/typescript.js:21774:13)
    at Object.updateSourceFile (/Users/klaus/code/wotan/node_modules/typescript/lib/typescript.js:21621:13)
    at Object.updateSourceFile (/Users/klaus/code/wotan/node_modules/typescript/lib/typescript.js:15752:47)
    at ProjectHost.updateSourceFile (/Users/klaus/code/wotan/packages/wotan/src/project-host.js:166:25)
```

This is likely caused by the incremental parser and therefore an external bug. Still this needs to be investigated and maybe reported in the TypeScript repo.

**Comment by ajafff** [comment]
The AST is somehow corrupted after the first update. Reducing the above code leads to `arrow-parens` crashing instead of emitting an invalid error:

```ts
export class Rule {
    private getPropertyInfo() {
        return
    }
}

(name) => b;
```

```
TypeError: Cannot read property 'end' of undefined
    at cb (/Users/klaus/code/wotan/node_modules/tslint/lib/rules/trailingCommaRule.js:163:133)
    at visitNode (/Users/klaus/code/wotan/node_modules/typescript/lib/typescript.js:15231:24)
    at Object.forEachChild (/Users/klaus/code/wotan/node_modules/typescript/lib/typescript.js:15475:24)
    at cb (/Users/klaus/code/wotan/node_modules/tslint/lib/rules/trailingCommaRule.js:170:23)
    at visitNodes (/Users/klaus/code/wotan/node_modules/typescript/lib/typescript.js:15240:30)
    at Object.forEachChild (/Users/klaus/code/wotan/node_modules/typescript/lib/typescript.js:15466:24)
    at TrailingCommaWalker.walk (/Users/klaus/code/wotan/node_modules/tslint/lib/rules/trailingCommaRule.js:172:19)
    at Rule.AbstractRule.applyWithWalker (/Users/klaus/code/wotan/node_modules/tslint/lib/language/rule/abstractRule.js:31:16)
    at Rule.apply (/Users/klaus/code/wotan/node_modules/tslint/lib/rules/trailingCommaRule.js:64:21)
    at _a.apply (/Users/klaus/code/wotan/packages/bifrost/src/index.js:29:44)
```

**Comment by ajafff** [comment]
reproduces with the following minimal tslint.json:

```json
{
  "rules": {
    "arrow-parens": true,
    "semicolon": [true, "always"],
    "trailing-comma": [true, {
      "singleline": "never",
      "multiline": "always"
    }]
  }
}

```

**Comment by ajafff** [comment]
Reproduces with the following minimal tsconfig.json:

```json
{
  "compilerOptions": {
    "importHelpers": true
  },
  "include": [
    "test.ts"
  ]
}
```
