### ISSUE TITLE
TypeError: tsutils_1.isCompilerOptionEnabled is not a function

### ISSUE THREAD

**Issue by AlCalzone** [fimbullinter/wotan#518]
I tried getting the language server plugin to work as described [here](https://github.com/fimbullinter/wotan/blob/master/packages/mithotyn/README.md). Since I did not see anything happen, I tried to execute `wotan` manually and got the following error:
```
TypeError: tsutils_1.isCompilerOptionEnabled is not a function
    at target.supports.combinePredicates (D:\ioBroker.tradfri\node_modules\@fimbul\ymir\src\index.js:74:88)
    at Function.supports (D:\ioBroker.tradfri\node_modules\@fimbul\ymir\src\index.js:48:71)
    at Linter.prepareRules (D:\ioBroker.tradfri\node_modules\@fimbul\wotan\src\linter.js:113:54)
    at Linter.getFindings (D:\ioBroker.tradfri\node_modules\@fimbul\wotan\src\linter.js:77:28)
    at Runner.lintProject (D:\ioBroker.tradfri\node_modules\@fimbul\wotan\src\runner.js:69:47)
    at lintProject.next (<anonymous>)
    at LintCommandRunner.run (D:\ioBroker.tradfri\node_modules\@fimbul\wotan\src\commands\lint.js:24:34)
    at Object.<anonymous> (D:\ioBroker.tradfri\node_modules\@fimbul\wotan\src\commands\index.js:25:30)
    at Generator.next (<anonymous>)
    at D:\ioBroker.tradfri\node_modules\tslib\tslib.js:107:75
```

Here are my config files in case this is of any help:
```
.fimbullinter.yaml:

config: .wotanrc.yaml
exclude:
  - "**/*.d.ts"
project: src/tsconfig.json
```

```
.wotanrc.yaml:

extends: wotan:recommended
```

**Comment by ajafff** [comment]
That's very strange. `isCompilerOptionEnabled` was introduced in `tsutils@2.29.0` and every package of this project depends on at least that version.

This is likely an issue with the package installer in use. Where exactly is `tsutils` located within `node_modules` (there may be multiple installations nested in other dependency's node_modules) and what's its version?
Can you also try deleting `node_modules` entirely and install everything from scratch?

---

To diagnose why the LanguageService Plugin isn't working, you can enable verbose logging (from https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin#debugging)

```sh
set TSS_LOG="-logToFile true -file C:\SomeFolder\MyTypeScriptLog.txt -level verbose"
code # or whatever editor you are using, make sure to end all processes of it before this
```

In VSCode you could also execute the command `TypeScript: Open TS Server Log.` (this prompts you to enable TS Server logging, after that execute it again to actually open the log).
You probably want to disable logging when you are done. It's somewhere in the user settings.

**Comment by AlCalzone** [comment]
Hmm I just tried again (fresh pull of the repo from github) and it worked. Probably something wrong in the node_modules.
